name: Reusable smoke_test

on:
  workflow_call:
    inputs:
      run_on:
        required: true
        type: string

jobs:
  smoke_test:
    name: smoke_test
    runs-on: ${{ inputs.run_on }}
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: setup Go 1.20
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install depend
        run: |
          python -m pip install pexpect
      - name: install
        run: make install
      - name: check rebuild
        id: check_rebuild
        working-directory: ./smoke_test
        run: | 
           python smoke_test.py
      - uses: nick-invision/assert-action@v1
        with:
          expected: "PASS"
          actual: ${{ steps.check_rebuild.outputs.value }}
