name: Smoke test

on:
  push:
  pull_request:

jobs:
  smoke_test_ubuntu:
    uses: ./.github/workflows/smoke_test_reuse_job.yml
    with:
      run_on: ubuntu-latest
  smoke_test_macos:
    uses: ./.github/workflows/smoke_test_reuse_job.yml
    with:
      run_on: macos-latest
  smoke_test_windows:
    uses: ./.github/workflows/smoke_test_reuse_job_windows.yml
    with:
      run_on: windows-latest
